In [2]:
#import numpy library
import numpy as np

In [3]:
#construct matrix
matrix = np.array([[1,0.2,0.5],[0.2,1,0.8,],[0.5,0.8,1]])
print(matrix)

[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


In [4]:
#a)Compute inversion of the matrix
matrix_inversion = np.linalg.inv(matrix)
print("Matrix inversion:")
print(matrix_inversion)

Matrix inversion:
[[ 1.56521739  0.86956522 -1.47826087]
 [ 0.86956522  3.26086957 -3.04347826]
 [-1.47826087 -3.04347826  4.17391304]]


In [5]:
#b)compute determinant of matrix
determinant = np.linalg.det(matrix)
print("Determinant:")
print(determinant)

Determinant:
0.2299999999999999


In [6]:
import scipy

In [7]:
#c)Decompose the matrix
#Using LU decomposition
from numpy import array 
from scipy.linalg import lu 

#define the square matrix
matrix = array([[1,0.2,0.5],[0.2,1,0.8],[0.5,0.8,1]])
print("matrix:")
print(matrix)

#LU decomposition
P,L,U = lu(matrix)
print("LU matrix")
print(P)
print(L)
print(U)

#then reconstruct the matrix
new_matrix = P.dot(L).dot(U)
print("new_matrix:")
print(new_matrix)

matrix:
[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]
LU matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1.         0.         0.        ]
 [0.2        1.         0.        ]
 [0.5        0.72916667 1.        ]]
[[1.         0.2        0.5       ]
 [0.         0.96       0.7       ]
 [0.         0.         0.23958333]]
new_matrix:
[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


In [17]:
#d)Transform the matrix
#transformation defined as matrix multiplication

#define the function
#using, L: R^3 TO R^3 which can be defined as L(X) = AX
def T(matrix):
    A = np.array([[1,0.2,0.5],[0.2,1,0.8],[0.5,0.8,1]])
    Transformed_matrix = A @ matrix
    return Transformed_matrix 

matrix = np.array([[1,0.2,0.5],[0.2,1,0.8],[0.5,0.8,1]])
Transformed_matrix = T(matrix)

print("Matrix:")
print(matrix)
print("The Transformed matrix is:")
print(Transformed_matrix)

Matrix:
[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]
The Transformed matrix is:
[[1.29 0.8  1.16]
 [0.8  1.68 1.7 ]
 [1.16 1.7  1.89]]
